- id: '1621789138280'
  alias: Front Room Cast
  description: ''
  trigger:
  - platform: device
    device_id: 0e900c9f4717d5dd812cc64060689548
    domain: media_player
    entity_id: media_player.front_room
    type: playing
  condition: []
  action:
  - type: turn_on
    device_id: c5cf3840aa9a5edc3f6730aeea7d27b4
    entity_id: switch.familyroomremote_front_room
    domain: switch
  mode: single
- id: '1622593051570'
  alias: Patio Cast
  description: ''
  trigger:
  - platform: device
    device_id: 2ca6e10337791df1d91127a6b6395514
    domain: media_player
    entity_id: media_player.patio_deck
    type: playing
  condition:
  - condition: device
    type: is_off
    device_id: e2f027ae06779650245eca8a0e090c80
    entity_id: remote.basementremote
    domain: remote
  action:
  - type: turn_on
    device_id: e2f027ae06779650245eca8a0e090c80
    entity_id: switch.basementremote_patio
    domain: switch
  mode: single