- id: '1617997463166'
  alias: PatioCameraMotion
  description: ''
  trigger:
  - platform: webhook
    webhook_id: patio_motion
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 6
      milliseconds: 0
  - service: notify.mobile_app_pat_s_phone
    data:
      data:
        image: /api/camera_proxy/camera.server_nas_patio_cam
      message: Patio
  - service: notify.mobile_app_mandy_s_phone
    data:
      message: Patio
      data:
        image: /api/camera_proxy/camera.server_nas_patio_cam
  mode: single
- id: '1618152173668'
  alias: Garage Motion
  description: ''
  trigger:
  - platform: webhook
    webhook_id: garage_motion
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 6
      milliseconds: 0
  - service: notify.mobile_app_pat_s_phone
    data:
      data:
        image: /api/camera_proxy/camera.server_nas_garage_cam
      message: Garage
  - service: notify.mobile_app_mandy_s_phone
    data:
      message: Garage
  mode: single
- id: '1620574270196'
  alias: FrontLightsOn
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: fcaae75413524cd2ec74234155a6ee84
    entity_id: switch.outside_front
    domain: switch
  mode: single
- id: '1620574324786'
  alias: FrontLightsOff
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: fcaae75413524cd2ec74234155a6ee84
    entity_id: switch.outside_front
    domain: switch
  mode: single
- id: '1621277671416'
  alias: BedroomLampsOn
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_off
      device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
      entity_id: light.mandys_bedside
      domain: light
    - condition: device
      type: is_off
      device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
      entity_id: light.pats_bedside
      domain: light
  action:
  - type: turn_on
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
    brightness_pct: 100
  mode: single
- id: '1621277785664'
  alias: BedroomLampsOff
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
      entity_id: light.mandys_bedside
      domain: light
    - condition: device
      type: is_on
      device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
      entity_id: light.pats_bedside
      domain: light
  action:
  - type: turn_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  - type: turn_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  mode: single
- id: '1621278013040'
  alias: LampsOnSwitch
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  - platform: device
    type: turned_on
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  condition:
  - condition: device
    type: is_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  action:
  - type: turn_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  mode: single
- id: '1621278084608'
  alias: LampsOffSwitch
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  - platform: device
    type: turned_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  condition:
  - condition: device
    type: is_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  - condition: device
    type: is_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  - condition: device
    type: is_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  action:
  - type: turn_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  mode: single
