- id: '1620574270196'
  alias: Front Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: fcaae75413524cd2ec74234155a6ee84
    entity_id: switch.outside_front
    domain: switch
  mode: single
- id: '1620574324786'
  alias: Front Lights Off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: fcaae75413524cd2ec74234155a6ee84
    entity_id: switch.outside_front
    domain: switch
  mode: single
- id: '1621277671416'
  alias: Bedroom Lamps On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_off
      device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
      entity_id: light.mandys_bedside
      domain: light
    - condition: device
      type: is_off
      device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
      entity_id: light.pats_bedside
      domain: light
  action:
  - type: turn_on
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
    brightness_pct: 100
  mode: single
- id: '1621277785664'
  alias: Bedroom Lamps Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
      entity_id: light.mandys_bedside
      domain: light
    - condition: device
      type: is_on
      device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
      entity_id: light.pats_bedside
      domain: light
  action:
  - type: turn_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  - type: turn_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  mode: single
- id: '1621278013040'
  alias: Lamps On Switch
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  - platform: device
    type: turned_on
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  condition:
  - condition: device
    type: is_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  action:
  - type: turn_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  mode: single
- id: '1621278084608'
  alias: Lamps Off Switch
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  - platform: device
    type: turned_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  condition:
  - condition: device
    type: is_on
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  - condition: device
    type: is_off
    device_id: 8ff30df3a7a04a9ec52ffaeabf36c31e
    entity_id: light.pats_bedside
    domain: light
  - condition: device
    type: is_off
    device_id: 4bd3e4a3b3a026f26b83273a9a95a92d
    entity_id: light.mandys_bedside
    domain: light
  action:
  - type: turn_off
    device_id: cbfab1119d03c69eb77e7000157eb296
    entity_id: switch.bedroom_main_lamps
    domain: switch
  mode: single
- id: '1621789138280'
  alias: Front Room Cast
  description: ''
  trigger:
  - platform: device
    device_id: 0e900c9f4717d5dd812cc64060689548
    domain: media_player
    entity_id: media_player.front_room
    type: playing
  condition: []
  action:
  - type: turn_on
    device_id: c5cf3840aa9a5edc3f6730aeea7d27b4
    entity_id: switch.familyroomremote_front_room
    domain: switch
  mode: single
- id: '1622217008219'
  alias: Washing Machine Done
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.washer_washer_machine_state
    from: run
    to: stop
  condition: []
  action:
  - device_id: 89c188c063143ba64a03d02b16ae3cb2
    domain: mobile_app
    type: notify
    title: Washing Machine Complete
    message: Washing Machine Complete
  mode: single
- id: '1622217098267'
  alias: Dryer Done
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dryer_dryer_machine_state
    from: run
    to: stop
  condition: []
  action:
  - device_id: 89c188c063143ba64a03d02b16ae3cb2
    domain: mobile_app
    type: notify
    title: Dryer Done
    message: Dryer Done
  mode: single
- id: '1622593051570'
  alias: Patio Cast
  description: ''
  trigger:
  - platform: device
    device_id: 2ca6e10337791df1d91127a6b6395514
    domain: media_player
    entity_id: media_player.patio_deck
    type: playing
  condition:
  - condition: device
    type: is_off
    device_id: e2f027ae06779650245eca8a0e090c80
    entity_id: remote.basementremote
    domain: remote
  action:
  - type: turn_on
    device_id: e2f027ae06779650245eca8a0e090c80
    entity_id: switch.basementremote_patio
    domain: switch
  mode: single
- id: '1622924414886'
  alias: Patio Motion
  description: ''
  trigger:
  - platform: mqtt
    topic: aimotion/triggers/patio
    payload: 'on'
    value_template: '{{ value_json.state }}'
  condition: []
  action:
  - service: notify.mobile_app_pat_s_phone
    data:
      message: Patio Motion
      title: Patio Motion
      data:
        image: https://camera.flanneryonline.com/{{ trigger.payload_json.basename
          }}
        clickAction: app://com.synology.DScam
  - service: notify.mobile_app_mandy_s_phone
    data:
      message: Patio Motion
      title: Patio Motion
      data:
        image: https://camera.flanneryonline.com/{{ trigger.payload_json.basename
          }}
  - service: automation.turn_off
    target:
      entity_id: automation.new_automation_2
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    target:
      entity_id: automation.new_automation_2
  mode: single
