
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named groups/
light: !include_dir_merge_list lights/
notify: !include_dir_merge_list notify/

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/

script: !include_dir_merge_named scripts/

scene ui: !include scenes.yaml
scene manual: !include_dir_merge_list scenes/

homeassistant:
  packages: !include_dir_named packages/

lovelace:
  mode: storage
  dashboards:
    lovelace-home:
      mode: yaml
      title: Home
      icon: mdi:home-circle
      show_in_sidebar: true
      filename: dashboards/home.yaml