
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named groups/

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/

script: !include_dir_merge_named scripts/

scene ui: !include scenes.yaml
scene manual: !include_dir_merge_named scenes/

light: !include_dir_merge_list light_groups/

homeassistant:
  packages: !include_dir_named packages