- alias: Front Room Cast
  description: ''
  trigger:
    # - id: casting_on
    #   entity_id: media_player.front_room
    #   platform: device
    #   domain: media_player
    #   type: playing
    - id: switch_on
      entity_id: switch.front_room_tv
      platform: state
      to: "on"
    - id: switch_off
      entity_id: switch.front_room_tv
      platform: state
      to: "off"
  condition: []
  action:
    - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: switch_on
              # - condition: trigger
              #   id: casting_on
        sequence:
          # - wait_template: "{{ is_state('remote.familyroomremote', 'off') }}"
          #   timeout: "00:00:15"
          - entity_id: switch.familyroomremote_front_room
            service: switch.turn_on
      - conditions:
          - condition: trigger
            id: switch_off
        sequence:
          # - wait_template: "{{ is_state('remote.familyroomremote', 'on') }}"
          #   timeout: "00:00:15"
          - entity_id: switch.familyroomremote_front_room
            service: switch.turn_off
  mode: single