- alias: Front Room TV Switch
  description: ''
  trigger:
    - id: switch_on
      entity_id: switch.front_room_tv
      platform: state
      to: "on"
    - id: switch_off
      entity_id: switch.front_room_tv
      platform: state
      to: "off"
  condition: []
  action:
    - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: switch_on
        sequence:
          - service: switch.turn_on
            entity_id: switch.remote_front_room
          - service: media_player.turn_on
            entity_id: media_player.m2_front_room
          - service: media_player.select_source
            data_template:
              source: "Front Room"
              entity_id: media_player.m2_front_room
      - conditions:
          - condition: trigger
            id: switch_off
        sequence:
          - service: switch.turn_off
            entity_id: switch.remote_front_room
          - service: media_player.turn_off
            entity_id: media_player.m2_front_room
  mode: single