- alias: Last Changed - Contact Sensors
  trigger:
    platform: state
    entity_id: binary_sensor.dog_food, binary_sensor.deck_entry, binary_sensor.patio_entry, binary_sensor.garage_entry, binary_sensor.front_door_entry
    from: 'off'
    to: 'on'
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.{{ trigger.to_state.object_id }}_last_changed
        datetime: '{{ now().timestamp() | timestamp_local }}'