- alias: Bathroom Main Humidity
  description: ''
  trigger:
    - id: high_humidity
      entity_id: sensor.bathroom_main_humidity
      platform: numeric_state
      above: 65
    - id: normal_humidity
      entity_id: sensor.bathroom_main_humidity
      platform: numeric_state
      below: 60
  condition: []
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: high_humidity
        sequence:
          - entity_id: switch.bathroom_main_fan
            service: switch.turn_on
          - entity_id: switch.bathroom_water_fan
            service: switch.turn_on
      - conditions:
        - condition: trigger
          id: normal_humidity
        sequence:
          - entity_id: switch.bathroom_main_fan
            service: switch.turn_off
          - entity_id: switch.bathroom_water_fan
            service: switch.turn_off
      default: []
  mode: single