- alias: Doorbell
  variables:
    local_url: !secret local_url
  trigger:
    - platform: state
      entity_id: switch.doorbell
      to: 'on'
      from: 'off'
  condition: []
  action:
    - service: notify.phones
      data:
        message: Doorbell
        title: Doorbell
        data:
          channel: 'Doorbell'
          ttl: 0
          priority: high
    - service: media_player.play_media
      target:
        entity_id: media_player.cast_kitchen_mini
      data:
        media_content_id: '{{local_url}}/local/doorbell.mp3'
        media_content_type: music
  mode: single