- alias: Doorbell
  description: ''
  variables:
    local_url: !secret local_url
  trigger:
    - platform: state
      entity_id: switch.doorbell
      to: 'off'
  condition: []
  action:
    - service: notify.phones
      data:
        message: Doorbell
        title: Doorbell
    - service: media_player.play_media
      target:
        entity_id: media_player.kitchen_speaker
      data:
        media_content_id: '{{local_url}}/local/doorbell.mp3'
        media_content_type: music
  mode: single