- alias: Washing Machine Done
  description: ''
  trigger:
    - platform: state
      entity_id: sensor.washer_state
      from: run
      to: stop
  condition: []
  action:
    - service: notify.mobile_app_mandy_s_phone
      data:
        message: Washing Machine Complete
        title: Washing Machine Complete
  mode: single
- alias: Dryer Done
  description: ''
  trigger:
    - platform: state
      entity_id: sensor.dryer_state
      from: run
      to: stop
  condition: []
  action:
    - service: notify.mobile_app_mandy_s_phone
      data:
        message: Dryer Complete
        title: Dryer Complete
  mode: single