- alias: Notifications - Security - Sump Pump Water Leak
  trigger:
    - entity_id: binary_sensor.sump_pump_water
      platform: state
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: notify.phones
      data:
        message: Sump Pump Water Leak
        title: Sump Pump Water Leak
        data:
          channel: 'Alarm'
          ttl: 0
          priority: high
  mode: single
