- platform: switch
  name: Bedroom Main Lamps
  entity_id: switch.bedroom_main_lamps
- platform: switch
  name: Front Hall
  entity_id: switch.front_hall
- platform: switch
  name: Outside Front
  entity_id: switch.outside_front
- platform: switch
  name: Stairs
  entity_id: switch.stairs