- alias: Switch - Zwave - Kitchen/FamilyRoom
  hide_entity: True
  trigger:
    - id: sun_up
      entity_id: sun.sun
      platform: state
      to: 'above_horizon'
    - id: sun_down
      entity_id: sun.sun
      platform: state
      to: 'below_horizon'
  condition: []
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: sun_up
        sequence:
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.familyroom
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 1
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.island
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 1
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.kitchen
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 1
      - conditions:
        - condition: trigger
          id: sun_down
        sequence:
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.familyroom
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 0
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.island
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 0
          - service: zwave_js.set_config_parameter
            target:
              entity_id: light.kitchen
            data:
              parameter: "Enable/Disable Switch Mode"
              value: 0
  mode: single