- platform: min_max
  name: Average Humidity
  type: mean
  entity_ids:
    - sensor.bathroom_humidity
    - sensor.guest_bathroom_humidity
    - sensor.powder_room_humidity
- platform: min_max
  name: Average Temperature
  type: mean
  entity_ids:
    - sensor.bathroom_temperature
    - sensor.guest_bathroom_temperature
    - sensor.powder_room_temperature
- platform: min_max
  name: Average Pressure
  type: mean
  entity_ids:
    - sensor.bathroom_pressure
    - sensor.guest_bathroom_pressure
    - sensor.powder_room_pressure
- platform: template
  sensors:
    outdoor_pressure:
      friendly_name: 'Outdoor Pressure'
      device_class: pressure
      unit_of_measurement: 'hPa'
      value_template: >-
        {{ float(states('sensor.outside_pressure_inhg')) * 33.863887 }}
    indoor_zero_pressure:
      friendly_name: 'Indoor Pressure'
      device_class: pressure
      unit_of_measurement: 'hPa'
      value_template: >-
        {{ float(states('sensor.outdoor_pressure')) - 1013.25 }}
    outdoor_zero_pressure:
      friendly_name: 'Outdoor Pressure'
      device_class: pressure
      unit_of_measurement: 'hPa'
      value_template: >-
        {{ float(states('sensor.average_pressure')) - 1013.25 }}

- platform: thermal_comfort
  sensors:
    outside:
      friendly_name: Outside Absolute Humidity
      temperature_sensor: sensor.outside_temperature
      humidity_sensor: sensor.outdoor_humidity
      sensor_types: absolutehumidity
    inside:
      friendly_name: Inside Absolute Humidity
      temperature_sensor: sensor.average_temperature
      humidity_sensor: sensor.average_humidity
      sensor_types: absolutehumidity
