- alias: Bedroom Lamps
  description: ''
  trigger:
    - id: pats_side_on
      entity_id: light.pats_bedside
      platform: state
      to: 'on'
    - id: pats_side_off
      entity_id: light.pats_bedside
      platform: state
      to: 'off'
    - id: mandys_side_on
      entity_id: light.mandys_bedside
      platform: state
      to: 'on'
    - id: mandys_side_off
      entity_id: light.mandys_bedside
      platform: state
      to: 'off'
    - id: switch_on
      entity_id: switch.bedroom_lamps
      platform: state
      to: 'on'
    - id: switch_off
      entity_id: switch.bedroom_lamps
      platform: state
      to: 'off'
  condition: []
  action:
    - choose:
      #on from switch
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.pats_bedside
              state: "off"
            - condition: state
              entity_id: light.mandys_bedside
              state: "on"
            - condition: trigger
              id: switch_on
        sequence:
          - entity_id: light.pats_bedside
            service: light.turn_on
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.mandys_bedside
              state: "off"
            - condition: state
              entity_id: light.pats_bedside
              state: "on"
            - condition: trigger
              id: switch_on
        sequence:
          - entity_id: light.mandys_bedside
            service: light.turn_on
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.mandys_bedside
              state: "off"
            - condition: state
              entity_id: light.pats_bedside
              state: "off"
            - condition: trigger
              id: switch_on
        sequence:
          - entity_id: light.mandys_bedside
            service: light.turn_on
          - entity_id: light.pats_bedside
            service: light.turn_on
      #off from switch
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.pats_bedside
              state: "on"
            - condition: state
              entity_id: light.mandys_bedside
              state: "off"
            - condition: trigger
              id: switch_off
        sequence:
          - entity_id: light.pats_bedside
            service: light.turn_off
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.mandys_bedside
              state: "on"
            - condition: state
              entity_id: light.pats_bedside
              state: "off"
            - condition: trigger
              id: switch_off
        sequence:
          - entity_id: light.mandys_bedside
            service: light.turn_off
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.mandys_bedside
              state: "on"
            - condition: state
              entity_id: light.pats_bedside
              state: "on"
            - condition: trigger
              id: switch_off
        sequence:
          - entity_id: light.mandys_bedside
            service: light.turn_off
          - entity_id: light.pats_bedside
            service: light.turn_off
      #on from lamps
      - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: mandys_side_on
                - condition: trigger
                  id: pats_side_on
            - condition: state
              entity_id: switch.bedroom_lamps
              state: "off"
        sequence:
          - entity_id: switch.bedroom_lamps
            service: switch.turn_on
      #off Mandys side
      - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: mandys_side_off
            - condition: state
              entity_id: light.pats_bedside
              state: "off"
            - condition: state
              entity_id: switch.bedroom_lamps
              state: "on"
        sequence:
          - entity_id: switch.bedroom_lamps
            service: switch.turn_off
      #off Pats side
      - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: pats_side_off
            - condition: state
              entity_id: light.mandys_bedside
              state: "off"
            - condition: state
              entity_id: switch.bedroom_lamps
              state: "on"
        sequence:
          - entity_id: switch.bedroom_lamps
            service: switch.turn_off
  mode: single