- alias: Front Lights
  description: ''
  trigger:
    - id: sun_up
      entity_id: sun.sun
      platform: state
      to: 'above_horizon'
    - id: sun_down
      entity_id: sun.sun
      platform: state
      to: 'below_horizon'
  condition: []
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: sun_up
        sequence:
          - entity_id: light.outside_front
            service: light.turn_off
      - conditions:
        - condition: trigger
          id: sun_down
        sequence:
          - entity_id: light.outside_front
            service: light.turn_on
  mode: single