- platform: group
  name: Whole House Lights
  entities:
    - light.mandys_bedside
    - light.pats_bedside
    - light.bedroom
    - light.familyroom
    - light.island
    - light.kitchen
    - light.breakfast
    - light.front_room
    - light.front_hall
    - light.stairs
    - light.garage