esphome:
  name: electric-panel
  platform: ESP32
  board: nodemcu-32s

substitutions:
  update_time: 10s
  gain_ct: '27518'
  gain_voltage: '7135'

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

time:
  - platform: sntp
    id: sntp_time

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:
  - platform: atm90e32
    cs_pin: 4
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
    phase_a:
      power:
        name: Furnace Watts
        id: furnace
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_b:
      power:
        name: Bedrooms Watts
        id: bedrooms
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_c:
      power:
        name: Second Floor Watts
        id: second_floor
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
  - platform: atm90e32
    cs_pin: 5
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
    phase_a:
      power:
        name: AC Watts
        id: ac
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_b:
      power:
        name: Right Phase A Watts
        id: right1
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_c:
      power:
        name: Right Phase B Watts
        id: right2
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
  - platform: atm90e32
    cs_pin: 0
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
    phase_a:
      power:
        name: Main Phase 1 Watts
        id: main1
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_b:
      power:
        name: Main Phase 2 Watts
        id: main2
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_c:
      power:
        name: Solar Watts
        id: solar
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
  - platform: atm90e32
    cs_pin: 16
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
    phase_a:
      power:
        name: Basement Watts
        id: basement
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_b:
      power:
        name: Utility Watts
        id: utilities
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}
    phase_c:
      power:
        name: Bathrooms Watts
        id: bathrooms
      gain_voltage: ${gain_voltage}
      gain_ct: ${gain_ct}

  #Solar
  - platform: total_daily_energy
    name: Solar kWh
    power_id: solar
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  #HVAC
  - platform: template
    name: HVAC Watts
    id: totalHvacWatts
    lambda: return id(furnace).state + id(ac).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: HVAC kWh
    power_id: totalHvacWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  #Main
  - platform: template
    name: Main Watts
    id: totalMainWatts
    lambda: return id(main1).state + id(main2).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}
  - platform: template
    name: Grid Input Watts
    id: GridInputWatts
    lambda: >-
      if (id(totalMainWatts).state > 0.0) {
        return 0.0 ;
      } else {
        return id(totalMainWatts).state * -1 ;
      }
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}
  - platform: template
    name: Grid Output Watts
    id: GridOutputWatts
    lambda: >-
      if (id(totalMainWatts).state < 0.0) {
        return 0.0 ;
      } else {
        return id(totalMainWatts).state ;
      }
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: Grid Input kWh
    power_id: GridInputWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: Grid Output kWh
    power_id: GridOutputWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  #Total Energy Used
  - platform: template
    name: Consumed Watts
    id: consumedWatts
    lambda: >-
      return
        id(utilities).state +
        id(furnace).state +
        id(bedrooms).state +
        id(basement).state +
        id(bathrooms).state +
        id(second_floor).state +
        id(ac).state +
        id(right1).state +
        id(right2).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: Consumed kWh
    power_id: consumedWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh