cloud:
config:
counter:
energy:
image:
logbook:
media_source:
mobile_app:
my:
person:
stream:
sun:
system_health:
timer:
updater:
webhook:
zone:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8

logger:
  default: error
  filters:
    pychromecast.socket_client:
      - "Failed to connect to service ServiceInfo"
      - "Error communicating with socket, resetting connection"
      - "Error reading from socket."
    homeassistant.components.nws:
      - "Error requesting NWS *"
    homeassistant.components.nfandroidtv.config_flow:
      - "Error connecting to device at *"
    homeassistant.components.plex.server:
      - "Could not connect to Plex server: *"
    aioharmony.harmonyclient:
      - "Unable to determine if XMPP is enabled*"
    aioharmony.hubconnector_websocket:
      - "Connection timed out for hub*"
    custom_components.frigate.api:
      - "Timeout error fetching information from *"
    custom_components.hacs:
      - "Timeout of 20 reached while waiting for *"

recorder:
  db_url: !secret mysql
  include:
    domains:
      - person
      - light
      - switch
    entity_globs:
      - binary_sensor.*_motion
      - binary_sensor.*_water
      - camera.*_person
      - sensor.*_kwh
      - sensor.*_watts
      - sensor.*_humidity
      - sensor.*_absolutehumidity
      - sensor.*_temperature
      - sensor.*_pressure
      - input_datetime.*_last_changed
    entities:
      - binary_sensor.garage_door_status
      - sensor.dryer_state
      - sensor.washer_state